version: '3.4'

services:

  redis:
    image: redis
    ports:
      - 6380:6379

  users:
    build: .
    environment:
      PORT: 9000
      MONGO_URI: mongodb://mongo
      MONGO_USER_COLLECTION_NAME: users
    ports:
      - 9000:9000

  outgoing-proxy-service:
    image: registry.gitlab.com/yesodot/rnd/terminal-rabaz/shared/spike-proxy-service
    environment:
      MODE: outgoing
      PORT: 9000
      SPIKE_REDIS_HOST: redis://redis
      SPIKE_CLIENT_ID: lvE9ErHNcKLGvL4gf8mXSgXr1dis3IDO7pTD8K8u
      SPIKE_CLIENT_SECRET: Kk3Xz9a5PZVnBK~BXJevvOlqE25tfI7uemD~WrsonsFrISpT0FMqukRfqn_8v_7i5nMpWZsb5Mc4G4wwfXxoj4VlyDTMZnH5klXC
      SPIKE_URL: http://51.144.178.121:1337
      OUTGOING_SERVICES: >
        [
          {
            "route": "/api/*",
            "target": "http://172.29.64.1:8000",
            "audience": "SuNbP8x1wZJ7RlUpBxkz6onhlFt1VD",
            "useBearerToken": true
          }
        ]

    sysctls:
      - net.ipv4.tcp_retries2=3 # this parameter improves redis connectivity
    ports:
      - 9001:9000
